<a href="https://colab.research.google.com/github/brandiegriffin83/brandiegriffin83/blob/main/L02_Brandy_Griffin_ITAI_2377.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!git clone https://github.com/patitimoner/itai2377-datasets.git

Cloning into 'itai2377-datasets'...
remote: Enumerating objects: 11, done.
remote: Counting objects: 100% (11/11), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 11 (delta 2), reused 9 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (11/11), 23.63 MiB | 27.56 MiB/s, done.
Resolving deltas: 100% (2/2), done.

In [2]:
%cd itai2377-datasets

/content/itai2377-datasets

In [3]:
!ls data/structured/

'Online Retail.xlsx'

In [4]:
import os
print(os.getcwd())
!ls

/content/itai2377-datasets
data  README.md

In [5]:
%cd data/structured
!ls

/content/itai2377-datasets/data/structured
'Online Retail.xlsx'

In [6]:
import pandas as pd

# Load structured dataset
df = pd.read_excel("Online Retail.xlsx")

# Display first few rows
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [7]:
from tensorflow.keras.datasets import cifar10

In [8]:
# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = cifar10.load_data()

# Display shapes of the datasets
print("Training data shape:", x_train.shape, y_train.shape)
print("Test data shape:", x_test.shape, y_test.shape)

Downloading data from https://www.cs.toronto.edu/~kriz/cifar-10-python.tar.gz
170498071/170498071 ━━━━━━━━━━━━━━━━━━━━ 2s 0us/step
Training data shape: (50000, 32, 32, 3) (50000, 1)
Test data shape: (10000, 32, 32, 3) (10000, 1)

In [9]:
import numpy as np

selected_images = []
selected_labels = []

for i in range(10):  # Loop through each class (0-9)
    idxs = np.where(y_train == i)[0][:10]  # Get indices for the first 10 images of each class
    selected_images.append(x_train[idxs])
    selected_labels.append(y_train[idxs])

selected_images = np.concatenate(selected_images)
selected_labels = np.concatenate(selected_labels)

print("Selected images shape:", selected_images.shape)
print("Selected labels shape:", selected_labels.shape)

Selected images shape: (100, 32, 32, 3)
Selected labels shape: (100, 1)

In [40]:
import os
import pandas as pd

In [41]:
%cd /content/itai2377-datasets
!ls

/content/itai2377-datasets
data  README.md

In [42]:
print(os.getcwd())
!ls

/content/itai2377-datasets
data  README.md

In [43]:
%cd data
!ls

/content/itai2377-datasets/data
structured  text

In [44]:
%cd text
!ls

/content/itai2377-datasets/data/text
bbc-news-data.csv

In [46]:
# Define the correct path to the CSV file
file_path = "bbc-news-data.csv"

# Load and display the CSV file
df = pd.read_csv(file_path)

# Display the first few rows of the dataframe
df.head()

,category\tfilename\ttitle\tcontent,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 154,Unnamed: 155,Unnamed: 156,Unnamed: 157,Unnamed: 158,Unnamed: 159,Unnamed: 160,Unnamed: 161,Unnamed: 162,Unnamed: 163
0,business\t001.txt\tAd sales boost Time Warner ...,from $639m year-earlier. The firm,which is now one of the biggest investors in ...,benefited from sales of high-speed internet c...,and less users for AOL. Time Warner said on ...,AOL,had has mixed fortunes. It lost 464,000 subscribers in the fourth quarter profits ...,the company said AOL's underlying profit befo...,which is close to concluding. Time Warner's ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,business\t003.txt\tYukos unit buyer faces loan...,so it will have to pay real money to the cred...,"said Moscow-based US lawyer Jamie Firestone, ...",we will fight them where the rule of law exis...,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,business\t004.txt\tHigh fuel prices hit BA's p...,the airline made a pre-tax profit of £75m ($1...,BA's chief executive,"said the results were ""respectable"" in a thir...",and it expects a rise in full-year revenues. ...,BA last year introduced a fuel surcharge for ...,it increased this from £6 to £10 one-way for ...,while the short-haul surcharge was raised fro...,further benefiting from a rise in cargo reven...,BA warned that yields - average revenues per ...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,business\t005.txt\tPernod takeover talk lifts ...,but has yet to contact its target. Allied Dom...,while Pernod shares in Paris slipped 1.2%. Pe...,the move which propelled it into the global t...,Pernod - at 7.5bn euros ($9.7bn) - is about 9...,which has a capitalisation of £5.7bn ($10.7bn...,one of Scotland's premier whisky firms,but lost out to luxury goods firm LVMH. Perno...,Havana Club rum and Jacob's Creek wine. Allie...,Courvoisier brandy,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,business\t006.txt\tJapan narrowly escapes rece...,figures show. Revised figures indicated grow...,the data suggests annual growth of just 0.2%,suggesting a much more hesitant recovery than...,and we will monitor developments carefully,said economy minister Heizo Takenaka. But in ...,"said Paul Sheard, economist at Lehman Brother...","said Rick Egelton, deputy chief economist at ...","said Ken Mayland, president of ClearView Econ...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
### How does AI process structured, image, and text data differently?

```python
### How does AI process structured, image, and text data differently?

AI processes different types of data in unique ways:

- **Structured Data**: This is like data you’d find in spreadsheets. AI uses things like machine learning algorithms and neural networks to find patterns and make sense of the numbers.

- **Image Data**: Image data involves pictures and photos. AI uses Convolutional Neural Networks (CNNs) to look at images, detect features like shapes and edges, and recognize objects.

- **Text Data**: Text data is all about words and language. AI uses Natural Language Processing (NLP) models to understand and analyze text. These models help AI figure out the meaning, context, and even the sentiment behind the words.

### What real-world AI applications combine multiple types of data (structured, image, text)?

There are lots of cool real-world AI applications that mix different types of data:

- **Healthcare**: AI can look at patient records (structured data), medical images like X-rays (image data), and doctors' notes (text data) to help diagnose diseases and suggest treatments.

- **Self-Driving Cars**: These cars use GPS data (structured data), camera feeds (image data), and traffic signs (text data) to drive safely and navigate roads.

- **Online Shopping**: AI in online stores uses your purchase history (structured data), product images (image data), and customer reviews (text data) to recommend products you might like.

### Imagine you're building an AI personal assistant. What type of data would it need?

If I were building an AI personal assistant, it would need different types of data:

- **Structured Data**: Things like your calendar events, contacts, and to-do lists to help manage your schedule and remind you of important tasks.

- **Image Data**: Visual inputs from cameras to recognize objects, faces, and even monitor your home for security purposes.

- **Text Data**: This includes all your voice commands and text messages so the assistant can understand your requests, answer questions, and have conversations with you.
```

- **Text Data**: Text data is all about words and language. AI uses Natural Language Processing (NLP) models to understand and analyze text. These models help AI figure out the meaning, context, and even the sentiment behind the words.

### What real-world AI applications combine multiple types of data (structured, image, text)?

There are lots of cool real-world AI applications that mix different types of data:

- **Healthcare**: AI can look at patient records (structured data), medical images like X-rays (image data), and doctors' notes (text data) to help diagnose diseases and suggest treatments.

- **Self-Driving Cars**: These cars use GPS data (structured data), camera feeds (image data), and traffic signs (text data) to drive safely and navigate roads.

- **Online Shopping**: AI in online stores uses your purchase history (structured data), product images (image data), and customer reviews (text data) to recommend products you might like.

### Imagine you're building an AI personal assistant. What type of data would it need?

If I were building an AI personal assistant, it would need different types of data:

- **Structured Data**: Things like your calendar events, contacts, and to-do lists to help manage your schedule and remind you of important tasks.

- **Image Data**: Visual inputs from cameras to recognize objects, faces, and even monitor your home for security purposes.

- **Text Data**: This includes all your voice commands and text messages so the assistant can understand your requests, answer questions, and have conversations with you.

SyntaxError: invalid character '’' (U+2019) (<ipython-input-54-16868ba585c6>, line 5)